[workspace]
members = [
    "drill-proto",
    "drill-client",
    "drill-server",
]
resolver = "2"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
