name: Build Docker Images
on: [push]

jobs:
  build-docker-image:
    name: Build Docker Image

    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert GITHUB_REPOSITORY into lowercase
        run: |
            echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build Docker Image
        run: |
            docker build \
              -t drill-server:latest \
              --build-arg FEATURES=dynamic,ao \
              .

      - name: Push Docker Image
        run: |
            docker tag drill-server:latest ghcr.io/${REPO}:latest
            docker push ghcr.io/${REPO}:latest
